name: doc_analyzer_env
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- pip:
  - azure-ai-formrecognizer>=3.2.0
  - azure-ai-ml>=1.4.0
  - torch>=1.12.0
  - Pillow>=9.0.0
  - pandas>=1.4.0
  - numpy>=1.21.0
  - transformers>=4.20.0
  - nougat-ocr>=0.1.0
  - fitz>=0.0.1
  - PyMuPDF>=1.19.0

