name: doc_analyzer_env
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- pip:
  - azure-ai-formrecognizer
  - azure-ai-ml
  - torch
  - Pillow
  - pandas
  - numpy
  - transformers
  - nougat-ocr
  - fitz
  - PyMuPDF

