name: chunk_caption_index_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - pip:
    - azureml-core
    - azure-ai-ml
    - azure-storage-blob
    - azure-search-documents>=11.4.0
    - openai>=1.0.0
    - pandas
    - pillow
    - python-dotenv
    - azure-identity
    - azureml-rag[faiss, hugging_face]
    - mlflow
    - numpy
    - uuid
    - tokenizers
    - tiktoken