name: chunk_caption_index_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.3.1
  - pip:
    - azureml-core
    - azure-ai-ml
    - azure-storage-blob
    - azure-search-documents
    - openai
    - pandas
    - python-dotenv
    - azure-identity
    - azureml-rag
    - mlflow